name = "Navigator Hugo"
license = "CC BY 3.0"
licenselink = "https://creativecommons.org/licenses/by/3.0/"
description = "Hugo port of the Themefisherâ€™s Navigator Template"
homepage = "https://github.com/themefisher/navigator-hugo"
tags = ['landing-page', 'business', 'agency-template', 'multilingual', 'themefisher', 'hugo-theme', 'hugo-templates', 'bootstrap', 'blog', 'responsive', 'clean', 'simple', 'company', 'projects', 'dark', 'creative', 'contact-form', 'custom-themes', 'mobile', 'flexbox', 'minimalistic', 'pages']
features = ['bootstrap4','responsive','multilingual']
min_version = "0.43"

[author]
  name = "Themefisher"
  homepage = "https://themefisher.com/"
